site_name: FastAPI CRUD Router
repo_url: https://github.com/awtkns/fastapi-crudrouter
repo_name: awtkns/fastapi-crudrouter
edit_uri: ''

theme:
  name: material
  palette:
    - scheme: primary
      primary: teal
      accent: amber
  icon:
    repo: fontawesome/brands/github-alt
    logo: octicons/zap-24
  favicon: assets/zap.svg
  language: en

# Nav
nav:
- FastAPI CRUD Router: index.md
- Generated Routes: routing.md
- Overidng Routes: overrides.md
- Backends:
    - SQLAlchemy: backends/sqlalchemy.md
    - In Memory: backends/memory.md

markdown_extensions:
  - extra
  - admonition
  - codehilite

extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/awtkns/fastapi-crudrouter
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/adam-watkins-yvr/
  - icon: fontawesome/solid/globe
    link: https://wtkns.dev

extra_css:
- css/termynal.css
extra_javascript:
- js/termynal.js